development:
  clients:
    default:
      database: vaultron_development
      hosts:
        - 192.168.59.103:27017
      options:

test:
  clients:
    default:
      database: vaultron_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%=  ENV['MONGOLAB_URI'] =>
