development:
  clients:
    default:
      database: vaultron_development
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: vaultron_test
      hosts:
        - 192.168.59.103:27017
      options:

production:
  clients:
    default:
      database: heroku_hxlb7hkx
      hosts:
        - ds031972.mongolab.com:31972
      options:
        user: heroku_hxlb7hkx
        password: kq64gkb1rbv51vp3vhecr3u42p
